In [2]:
import pandas as pd

df = pd.read_excel("Online Retail.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [4]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

DATA CLEANING

Remove Missing Value

In [5]:
df = df.dropna(subset=['CustomerID'])

Remove Negative Quantities

In [6]:
df = df[df['Quantity'] > 0]

Remove canceled Order

In [7]:
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

FEATURE ENGINEERING

Create total price

In [8]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

Convert date

In [9]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

Extract Month

In [10]:
df['Month'] = df['InvoiceDate'].dt.month

Exploratory Data Analysis (EDA)

Monthly Revenue

In [11]:
df.groupby('Month')['TotalPrice'].sum()

Month
1      569445.040
2      447137.350
3      595500.760
4      469200.361
5      678594.560
6      661213.690
7      600091.011
8      645343.900
9      952838.382
10    1039318.790
11    1161817.380
12    1090906.680
Name: TotalPrice, dtype: float64

Top customers

In [12]:
df.groupby('CustomerID')['TotalPrice'].sum().sort_values(ascending=False)

CustomerID
14646.0    280206.02
18102.0    259657.30
17450.0    194550.79
16446.0    168472.50
14911.0    143825.06
             ...
17956.0        12.75
16454.0         6.90
14792.0         6.20
16738.0         3.75
13256.0         0.00
Name: TotalPrice, Length: 4339, dtype: float64

Top products

In [13]:
df.groupby('Description')['Quantity'].sum().sort_values(ascending=False)

Description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        77916
WORLD WAR 2 GLIDERS ASSTD DESIGNS     54415
JUMBO BAG RED RETROSPOT               46181
WHITE HANGING HEART T-LIGHT HOLDER    36725
                                      ...
SILVER AND BLACK ORBIT NECKLACE           1
HEN HOUSE W CHICK IN NEST                 1
NECKLACE+BRACELET SET PINK DAISY          1
NEW BAROQUE B'FLY NECKLACE PINK           1
FRYING PAN RED POLKADOT                   1
Name: Quantity, Length: 3877, dtype: int64

RFM Analysis

In [14]:
# Step 1: Define snapshot date (latest date in dataset)
snapshot_date = df['InvoiceDate'].max()

# Step 2: Create RFM table
rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,  # Recency
    'InvoiceNo': 'count',   # Frequency
    'TotalPrice': 'sum'     # Monetary
})

# Step 3: Rename columns
rfm.columns = ['Recency', 'Frequency', 'Monetary']

# Step 4: Check
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346.0         325          1  77183.60
12347.0           1        182   4310.00
12348.0          74         31   1797.24
12349.0          18         73   1757.55
12350.0         309         17    334.40

In [15]:
rfm['R_Score'] = pd.qcut(rfm['Recency'], 4, labels=[4,3,2,1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'], 4, labels=[1,2,3,4])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], 4, labels=[1,2,3,4])

rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

In [16]:
rfm.head()

            Recency  Frequency  Monetary R_Score F_Score M_Score RFM_Score
CustomerID
12346.0         325          1  77183.60       1       1       4       114
12347.0           1        182   4310.00       4       4       4       444
12348.0          74         31   1797.24       2       2       4       224
12349.0          18         73   1757.55       3       3       4       334
12350.0         309         17    334.40       1       1       2       112

In [17]:
rfm.to_csv("rfm_data.csv")
df.to_csv("cleaned_data.csv")